<definitions name="opinionAnalisysService"
   targetNamespace="http://www.opinionWorks.com/wsdl/opinionAnalisysService.wsdl"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:tns="http://www.opinionWorks.com/wsdl/opinionAnalisysService.wsdl"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 
   <message name="opinionAssesmentRequest">
      <part name="opinion" type="xsd:string"/>
   </message>
   <message name="opinionAssesmentResponse">
      <part name="opinionAnalisys" type="xsd:string"/>
   </message>

   <portType name="Opinion_PortType">
      <operation name="assessOpinion">
         <input message="tns:opinionAssesmentRequest"/>
         <output message="tns:opinionAssesmentResponse"/>
      </operation>
   </portType>

   <binding name="Opinion_Binding" type="tns:Opinion_PortType">
   <soap:binding style="rpc"
      transport="http://schemas.xmlsoap.org/soap/http"/>
   <operation name="assessOpinion">
      <soap:operation soapAction="assessOpinion"/>
      <input>
         <soap:body
            encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
            namespace="urn:opinionWorks:opinionAnalisysService"
            use="encoded"/>
      </input>
      <output>
         <soap:body
            encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
            namespace="urn:opinionWorks:opinionAnalisysService"
            use="encoded"/>
      </output>
   </operation>
   </binding>

   <service name="opinionAnalisys_Service">
      <documentation>WSDL File for the opinion analisys web service</documentation>
      <port binding="tns:Opinion_Binding" name="Hello_Port">
         <soap:address
            location="http://www.opinionWorks.com/assessOpinion/"/>
      </port>
   </service>
</definitions>